fix youtube cookie consent check (#238)
before this fix, python 3.11 would fail like this:
AttributeError: 'str' object has no attribute 'value'

assuming that socs.value is the correct way to retrieve the value in
some versions of python, avoid the issue by casting to string